Always Run 'Maven Build Status' Step (#855)
Since it is a required check for merging,
even for non-java Pull Requests.

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -139,15 +139,25 @@ jobs:
   maven-build-status:
     name: Maven Build Status
     needs: [ detect-changes, build ]
-    if: github.event.pull_request.draft == false || github.event_name == 'push'
+    if: always() && (github.event.pull_request.draft == false || github.event_name == 'push')
     runs-on: ubuntu-latest
     steps:
       - name: Check build status
         run: |
-          if [ "${{ needs.build.result }}" == "success" ] || [ "${{ needs.build.result }}" == "skipped" ]; then
-            echo "Build successful or skipped (as expected)."
+          if [ "${{ needs.detect-changes.outputs.should_run }}" == "true" ]; then
+            if [ "${{ needs.build.result }}" == "success" ]; then
+              echo "Build successful!"
+              exit 0
+            else
+              echo "Build failed or was cancelled."
+              exit 1
+            fi
+          fi
+          
+          if [ "${{ needs.detect-changes.outputs.should_run }}" == "false" ]; then
+            echo "Build was skipped (as expected)."
             exit 0
           else
-            echo "Build failed or cancelled."
+            echo "Unexpected outcome."
             exit 1
           fi
